name: Flash Attention Test Simple

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Flash attention version'
        default: 'v2.6.3'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Clone flash-attention
        run: |
          git clone --depth 1 --branch ${{ inputs.version }} https://github.com/Dao-AILab/flash-attention.git fa-src
          ls -la fa-src/
          
      - name: Test result
        run: echo "Flash attention ${{ inputs.version }} cloned successfully" 